# Generated by Django 4.0.3 on 2022-04-06 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='profile',
        ),
        migrations.AddField(
            model_name='feed',
            name='profile',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
