# Generated by Django 4.0.3 on 2022-04-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='profile',
            new_name='profile_id',
        ),
    ]
