# Generated by Django 4.0.3 on 2022-04-11 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_profile_feed_profile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='profile_id',
            new_name='profile',
        ),
    ]
